from __future__ import annotations

import argparse
from pathlib import Path

from .app import create_app


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="CMFGEN model results viewer")
    parser.add_argument(
        "-d",
        "--dir",
        dest="basepath",
        default=".",
        help="Directory to browse (default: current directory)",
    )
    parser.add_argument(
        "-p",
        "--port",
        dest="port",
        type=int,
        default=5567,
        help="Port to bind (default: 5567)",
    )
    parser.add_argument(
        "--host",
        dest="host",
        default="127.0.0.1",
        help="Host interface to bind (default: 127.0.0.1)",
    )
    parser.add_argument(
        "-a",
        "--all",
        dest="show_all",
        action="store_true",
        help="Show hidden files and directories",
    )
    parser.add_argument(
        "--debug",
        dest="debug",
        action="store_true",
        help="Enable Flask debug mode",
    )
    parser.add_argument(
        "-s",
        "--secret",
        dest="secret",
        default=None,
        help="Flask secret key; random key is generated by default",
    )
    return parser


def main(argv: list[str] | None = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)

    basepath = Path(args.basepath).expanduser().resolve()
    if not basepath.exists() or not basepath.is_dir():
        parser.error(f"--dir must point to an existing directory: {basepath}")

    app = create_app(
        basepath=str(basepath),
        show_all=args.show_all,
        secret_key=args.secret,
    )
    app.run(host=args.host, port=args.port, debug=args.debug)
